name: Dispatch Test

on:
  workflow_dispatch:
    inputs:
      env:
          type: choice
          description: select deploy environment
          required: true
          options:
            - development
            - staging
            - production
      #in case of deploying to multiregion
      region:
        type: choice
        required: false
        description: "Choose Region for production\n(for MultiRegion Release only)"
        options:
          - Tokyo
          - Seoul
          - Oregon
          - Frankfurt
      
      #in case of releasing lambda-billing
      function:
        type: choice
        required: false
        description: Choose Function to deploy (for Releasing Lambda only)
        options:
            - all
            - appleIapWebhook
            - cancelSubscription
            - createCustomSubscription
            - createSession
            - createSubscription
            - createSubscriptionCouponOnly
            - deleteCouponServer
            - deleteCustomer
            - getCoupon
            - getCouponServer
            - getInvoices
            - getSession
            - getSubscription
            - getUpcomingInvoice
            - issueCouponServer
            - pollingAppleIapReceipt
            - pollingCustomSubscription
            - resumeSubscription
            - stripeWebhook
            - updateCustomSubscription
            - updateSubscription

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Check if region input is provided
        run: |
          if [[ "${{ github.event.inputs.region }}" == "null" ]]; then
            echo "Region input not provided"
          else
            echo "Region input provided: ${{ github.event.inputs.region }}"
          fi
        shell: bash
