name: Dispatch Test

on:
  workflow_dispatch:
    inputs:
      env:
          type: choice
          description: select deploy environment
          required: true
          options:
            - development
            - staging
            - production
      #in case of deploying to multiregion
      region:
        type: choice
        required: true
        description: Choose Region for production (only for ECS-MultiRegion deployment)
        options:
          - Tokyo
          - Seoul
          - Oregon
          - Frankfurt
          - Skip (Not deploying to ECS-MultiRegion)
        default: Skip (Not deploying to ECS-MultiRegion)

env:
  INPUT_ENV: ${{ github.event.inputs.env }}
  INPUT_REGION: ${{ github.event.inputs.region }}
      
jobs:
  TESTS:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v4.1.1
        
      # - name: test composite action with inputs
      #   uses: ./.github/actions/test/test/
      #   with:
      #     IS_SUCCESS: ${{ success() }}
      #     WEBHOOK: 'hello'
      #     TITLE: ${{ contains( github.repository, '/READ' ) && format('DEPLOYMENT SUCCESS in {0}', env.INPUT_ENV) || format('DEPLOYMENT SUCCESS in {0} - {1}', env.INPUT_ENV, env.INPUT_REGION) }}
      #     MESSAGE: ${{ github.repository }}
          
      - name: set Message String to Show
        run: |
          echo "${{ contains( github.repository, '/READ' ) && format('DEPLOYMENT SUCCESS in {0}', env.INPUT_ENV) || format('DEPLOYMENT SUCCESS in {0} - {1}', env.INPUT_ENV, env.INPUT_REGION) }}"

      - name: print SUCCESS()
        run: |
          echo "${{ success() }}"
    # steps:
    #   - name: Check if region input is provided
    #     run: |
    #       if [[ "${{ github.event.inputs.region }}" == "null" ]]; then
    #         echo "Region input not provided"
    #       else
    #         echo "Region input provided: ${{ github.event.inputs.region }}"
    #       fi
    #     shell: bash

    #   - name: condition test
    #     run: |     
    #       echo "RESULT=${{ github.event_name == 'push' && 'PUSH_EVENT' || 'OTHER_EVENT' }}" >> $GITHUB_ENV
    #       echo "${{ github.event_name == 'push' && 'PUSH_EVENT' || 'OTHER_EVENT' }}"
        
