name: Sample Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  Hoolah:
    runs-on: ubuntu-latetest
    steps:
    - name: testtest
    # Check if workflow call runs properly
      uses: ./.github/workflows/set-common-env.yml
